site_name: CausalFlow
site_author: 'Luca Castri'
site_url: https://lcastri.github.io/howto

theme:
  name: 'material'
  palette:
    
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: orange
      accent: light blue
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    
    # Dark Mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: orange
      accent: light blue
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

  logo: assets/causalflow_logo.png
  favicon: assets/causalflow_icon.png


plugins:
  - search
  - mkdocstrings


nav:
  - Overview: index.md
  - CausalFlow: causalflow.md
  - Causal Graph: graph.md
  - Feature Selection Methods: feature_selection_method.md
  - RandomDAG: random_system.md
  - Preprocessing: preprocessing.md
  - Subsampling: subsampling_method.md
  - Basics: basics.md
