site_name: CausalFlow
site_author: 'Luca Castri'

theme:
  name: 'material'
  palette:
    
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: orange
      accent: light blue
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    
    # Dark Mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: orange
      accent: light blue
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

  logo: assets/causalflow_logo.png
  favicon: assets/causalflow_icon.png


plugins:
  - search
  - mkdocstrings

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/MathJax.js?config=TeX-AMS-MML_HTMLorMML

markdown_extensions:
  - mdx_math
  
nav:
  - Overview: index.md
  - Preprocessing: preprocessing.md
  - Graph: graph.md
  - Feature Selection Methods: feature_selection_method.md
  - Causal Discovery: causal_discovery.md
  - F-PCMCI: FPCMCI.md
  - CAnDOIT: CAnDOIT.md
  - RandomGraph: random_system.md
  - Utilities: basics.md
